name: C/C++ mac

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: brew install bison flex cmake
    - name: tarsinstall
      run: git clone https://github.com/TarsCloud/TarsCpp.git --recursive;cd TarsCpp;mkdir build;cd build;cmake .. -DTARS_MYSQL=OFF;make -j4;sudo make install
    - name: configure
      run: mkdir build;cd build;cmake ..
    - name: make
      run: cd build; make

