name: C/C++ linux

on: 
  push:
    branches:
    - master
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get install -y bison flex cmake psmisc libncurses5-dev zlib1g-dev; cmake --version
    - name: tarsinstall
      run: git clone https://github.com/TarsCloud/TarsCpp.git --recursive;cd TarsCpp;mkdir build;cd build;cmake .. -DTARS_MYSQL=OFF;make -j4;sudo make install
    - name: configure
      run: mkdir build;cd build;cmake ..
    - name: make
      run: cd build; make
